import cssConstants from './css/_constants.scss';

const MILISECONDS_BETWEEN_QUESTIONS = 1000;
const NUMBER_OF_QUESTIONS_PER_PLAYER = 1;
const SECONDS_PER_QUESTION_WITH_TIMER = +cssConstants.timerSeconds;

export {
    MILISECONDS_BETWEEN_QUESTIONS,
    NUMBER_OF_QUESTIONS_PER_PLAYER,
    SECONDS_PER_QUESTION_WITH_TIMER,
};